### ISSUE TITLE
Backfill not working - throws errors - backtesting 

### ISSUE THREAD

**Issue by d-fay** [nedievas/zenbot#4]
**Command `./zenbot map --backfill` thowing javascript error. Does not work.** 

When attempting to backtest using command `./zenbot sim --verbose` **backfill has not retrieved necessary historical data.** Here is example output: 
```
[    reporter]       h413104      18 trades.                      RSI:n/a bitfinex.BTC-USD BAL:         n/a ROI:n/a
[      trader] bitfinex.BTC-USD need more historical data, only have 0 of 26 5m ticks
[      trader] bitfinex.BTC-USD need more historical data, only have 0 of 26 5m ticks
[      trader] bitfinex.BTC-USD need more historical data, only have 0 of 26 5m ticks
[      trader] bitfinex.BTC-USD need more historical data, only have 0 of 26 5m ticks
[      trader] bitfinex.BTC-USD need more historical data, only have 0 of 26 5m ticks
[      trader] bitfinex.BTC-USD need more historical data, only have 0 of 26 5m ticks
[      trader] bitfinex.BTC-USD need more historical data, only have 0 of 26 5m ticks
[      trader] bitfinex.BTC-USD need more historical data, only have 0 of 26 5m ticks
[      trader] bitfinex.BTC-USD need more historical data, only have 0 of 26 5m ticks
[    reporter]       h413105      33 trades.                      RSI:n/a bitfinex.BTC-USD BAL:         n/a ROI:n/a
[      trader] bitfinex.BTC-USD need more historical data, only have 0 of 26 5m ticks
[      trader] bitfinex.BTC-USD need more historical data, only have 0 of 26 5m ticks
[      trader] bitfinex.BTC-USD need more historical data, only have 0 of 26 5m ticks
[      trader] bitfinex.BTC-USD need more historical data, only have 0 of 26 5m ticks
[      trader] bitfinex.BTC-USD need more historical data, only have 0 of 26 5m ticks
[      trader] bitfinex.BTC-USD need more historical data, only have 0 of 26 5m ticks
[      trader] bitfinex.BTC-USD need more historical data, only have 0 of 26 5m ticks
[      trader] bitfinex.BTC-USD need more historical data, only have 0 of 26 5m ticks
[      trader] bitfinex.BTC-USD need more historical data, only have 0 of 26 5m ticks
[      trader] bitfinex.BTC-USD need more historical data, only have 0 of 26 5m ticks
[      trader] bitfinex.BTC-USD need more historical data, only have 0 of 26 5m ticks
```
_Note: backtesting does work on recent data obtained from actively running zenbot in trading mode. The real issue here is that backfill is not properly working._

**Here is a log output of the isolated backfill command `./zenbot map --backfill` intended to retrieve historical data:**
```
computer:zenbot-bitfinex usrnm$ ./zenbot map --backfill
[    launcher] cmd `map` booting
/Users/usrnm/zenbot-bitfinex/utils/get_products.js:6
      if (c.assets.indexOf(product.asset) === -1) return false
                  ^

TypeError: Cannot read property 'indexOf' of undefined
    at /Users/usrnm/zenbot-bitfinex/utils/get_products.js:6:19
    at Array.filter (native)
    at get_products (/Users/usrnm/zenbot-bitfinex/utils/get_products.js:5:23)
    at mapper (/Users/usrnm/zenbot-bitfinex/plugins/bitfinex/backfiller.js:12:20)
    at /Users/usrnm/zenbot-bitfinex/node_modules/run-parallel/index.js:41:7
    at Array.forEach (native)
    at module.exports (/Users/usrnm/zenbot-bitfinex/node_modules/run-parallel/index.js:40:11)
    at mapper (/Users/usrnm/zenbot-bitfinex/node_modules/zenbrain/core/mapper/mapper.js:9:5)
    at Object.<anonymous> (/Users/usrnm/zenbot-bitfinex/node_modules/zenbrain/core/launcher/launcher.js:76:11)
    at Immediate.<anonymous> (/Users/usrnm/zenbot-bitfinex/node_modules/sosa/api.js:15:12)
```

This has been an issue in carlos8f's original repo as well and is not unique to your fork.

(Note: I have api keys properly connecting to Bitfinex and have verified that `./run.sh` trades and obtains real-time data.)

**Comment by nedievas** [comment]
Sorry, I think the problem is poor documentation. 
I have no problem with backfill and simulation.

To backfill:
`./zenbot launch map --backfill --config config_btc_usd.js`
(Error in Javascript is because you forgot _launch_ and selected _pair_ config to backfill).

To sim:
`./zenbot sim --verbose`
This `[      trader] bitfinex.BTC-USD need more historical data, only have 0 of 26 5m ticks` is normal. You have to wait longer and will see the filling ticks. Another way is to skip _--verbose_, so you'll only see the result of sim;)

**Comment by d-fay** [comment]
_I will try this on fedora but, the original ZenBot was designed for macOS, so my assumption is that me doing this on a mac is not causing issues._ 

The backfill command you provided runs, but does not actually pull any historical data.. it just starts recording real-time data. You're telling me that I need to run this for three months before I have enough data to backtest? 
```
[    launcher] cmd `launch` booting
[    launcher] cmd `map` booting
[    bitfinex]    m24858558    1000 trades. 04/06/2017 03:18:11 PM MDT SELL      1063.853 at     $1,201.59 BTC/USD
[    bitfinex]    m24858558   49999 trades. 04/06/2017 03:18:11 PM MDT SELL     26872.758 at     $1,151.95 BTC/USD
[    bitfinex]    m24858558      21 trades. 04/06/2017 03:18:31 PM MDT  BUY        17.598 at     $1,204.85 BTC/USD
[    bitfinex]    m24858558   49999 trades. 04/06/2017 03:18:31 PM MDT SELL     26859.328 at     $1,151.97 BTC/USD
[    bitfinex]    m24858558      24 trades. 04/06/2017 03:18:46 PM MDT  BUY        26.607 at     $1,203.95 BTC/USD
[    bitfinex]    m24858558   49999 trades. 04/06/2017 03:18:46 PM MDT SELL     26863.296 at     $1,152.01 BTC/USD
[    bitfinex]    m24858559      47 trades. 04/06/2017 03:19:21 PM MDT  BUY        23.949 at     $1,203.26 BTC/USD
[    bitfinex]    m24858559   49999 trades. 04/06/2017 03:19:21 PM MDT SELL     26865.431 at     $1,152.09 BTC/USD
[    bitfinex]    m24858559      80 trades. 04/06/2017 03:19:52 PM MDT  BUY        81.317 at     $1,201.10 BTC/USD
[    bitfinex]    m24858559   49999 trades. 04/06/2017 03:19:48 PM MDT SELL     26861.127 at     $1,152.21 BTC/USD
[    bitfinex]    m24858560      85 trades. 04/06/2017 03:20:13 PM MDT  BUY        55.292 at     $1,199.22 BTC/USD
[    bitfinex]    m24858560   49999 trades. 04/06/2017 03:20:12 PM MDT SELL     26852.817 at     $1,152.35 BTC/USD
```

**Comment by nedievas** [comment]
Bitfinex does not provide historical data. It has limitations. 49999 is the maximum I have found.

**Comment by nedievas** [comment]
Changed limit to 100.
