### ISSUE TITLE
Error: ETIMEDOUT crash

### ISSUE THREAD

**Issue by nedievas** [nedievas/zenbot#8]
```
[bfxbot@gene zenbot]$ ./zenbot.sh trade bitfinex.btc-usd
fetching pre-roll data:
cannot backfill bitfinex.BTC-USD: exchange does not offer historical data
               DATE            PRICE     DIFF            VOL         RSI                         ACTIONS                      BAL                PROFIT
2017-05-21 08:00:00    2069.20 USD              647
2017-05-21 09:00:00    2067.10 USD   -0.1%      334
2017-05-21 10:00:00    2074.00 USD   +0.3%      110
2017-05-21 20:00:00    2024.30 USD   -2.4%      534
2017-05-21 21:00:00    2019.40 USD   -0.2%      536
2017-05-21 22:00:00    2022.80 USD   +0.2%      816
2017-05-21 23:00:00    2025.00 USD   +0.1%      466
2017-05-22 00:00:00    2018.20 USD   -0.3%      896
2017-05-22 01:00:00    2023.80 USD   +0.3%      574
2017-05-22 02:00:00    2024.30 USD   +0.0%        2
2017-05-22 07:00:00    2083.70 USD   +2.9%      226
2017-05-22 08:00:00    2084.00 USD   +0.0%      652
2017-05-22 09:00:00    2134.00 USD   +2.4%     1982
2017-05-22 10:00:00    2140.60 USD   +0.3%     1013
2017-05-22 11:00:00    2155.60 USD   +0.7%     1277   ---
---------------------------- STARTING LIVE TRADING ----------------------------
2017-05-22 12:00:00    2166.80 USD   +0.5%    20519    --                         0.00000 BTC  39.11 USD    +0.0%   +0.0%
2017-05-22 13:00:00    2128.90 USD   -1.7%    68243   ---                         0.00000 BTC  39.11 USD    +0.0%   +1.8%
2017-05-22 13:15:10    2147.40 USD   +0.9%     3273    --                         0.00000 BTC  39.11 USD    +0.0%   +0.9%Error: Error: ETIMEDOUT
    at Request._callback (/home/bfxbot/zenbot/node_modules/bitfinex-api-node/rest.js:82:23)
    at self.callback (/home/bfxbot/zenbot/node_modules/request/request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Timeout._onTimeout (/home/bfxbot/zenbot/node_modules/request/request.js:762:12)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
aborting!
```
Suppose, I have to code some error handling to autorestart on such uninformative errors.

**Comment by eigilb** [comment]
For some strange reason I could not open a new issue, so I m posting it here.
I am getting this error after a fresh install (git clone https://github.com/nedievas/zenbot.git)
Both GDAX from carlos8f/zenbot and my own Bitstamp extension based on the same is running smooth.
It is tried on 2 different computers (one CentOS 7 and one Ubuntu 16.10) just to make sure it is not any conflicts in the mongo db. Same issue on both.

```
[eigilb@tb zenbot-nedievas]$ ./zenbot.sh trade bitfinex.LTC-USD
/home/eigilb/Prosjekt/Z/zenbot-nedievas/node_modules/mongodb/lib/url_parser.js:89
      throw new Error('double colon in host identifier');
      ^

Error: double colon in host identifier
    at module.exports (/home/eigilb/Prosjekt/Z/zenbot-nedievas/node_modules/mongodb/lib/url_parser.js:89:13)
    at connect (/home/eigilb/Prosjekt/Z/zenbot-nedievas/node_modules/mongodb/lib/mongo_client.js:403:16)
    at Function.MongoClient.connect (/home/eigilb/Prosjekt/Z/zenbot-nedievas/node_modules/mongodb/lib/mongo_client.js:227:3)
    at module.exports (/home/eigilb/Prosjekt/Z/zenbot-nedievas/boot.js:35:34)
    at Object.<anonymous> (/home/eigilb/Prosjekt/Z/zenbot-nedievas/zenbot.sh:12:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
[eigilb@tb zenbot-nedievas]$ 
```

**Comment by nedievas** [comment]
sorry.You should clone zenbot 4 from carlos8f, and take extensions/bitfinex from my repo. My repo is broken as it's not updated.

**Comment by nedievas** [comment]
I will create new repo Bitfinex extension for Zenbot 4
